// Generated by CoffeeScript 1.9.3
(function() {
  var boardShape, combinePaths, gatherPoints, traversePoints;

  gatherPoints = require('./_gather-points');

  traversePoints = require('./_traverse-points');

  combinePaths = function(src, target) {
    return src.path.d = src.path.d.concat(target.path.d);
  };

  boardShape = function(paths) {
    var key, manifolds, p, pathHash, tool, traversal;
    pathHash = {};
    while (paths.length) {
      p = paths.pop();
      tool = p.path['stroke-width'];
      if (pathHash[tool] != null) {
        combinePaths(pathHash[tool], p);
      } else {
        pathHash[tool] = p;
      }
    }
    manifolds = [];
    for (key in pathHash) {
      p = pathHash[key];
      traversal = traversePoints(gatherPoints(p.path.d));
      p.path.d = traversal.path;
      manifolds.push(traversal.manifold);
      paths.push(p);
    }
    return manifolds;
  };

  module.exports = boardShape;

}).call(this);
