// Generated by CoffeeScript 1.10.0
(function() {
  var BoundingBox, layerProperties;

  BoundingBox = require('./_bounding-box');

  layerProperties = function(svgObj) {
    var props;
    props = {};
    props.units = svgObj.svg.width.slice(-2);
    props.scale = parseFloat(svgObj.svg.width) / svgObj.svg.viewBox[2];
    props.bBox = new BoundingBox(svgObj.svg.viewBox);
    return props;
  };

  module.exports = layerProperties;

}).call(this);
