// Generated by CoffeeScript 1.9.3
(function() {
  var DEFAULT_SVG, boardStackup, sortLayers, stackLayers;

  sortLayers = require('./_sort-layers');

  stackLayers = require('./_stack-layers');

  DEFAULT_SVG = function(side, boardId) {
    return {
      svg: {
        xmlns: 'http://www.w3.org/2000/svg',
        version: '1.1',
        'xmlns:xlink': 'http://www.w3.org/1999/xlink',
        'stroke-width': '0',
        'stroke-linecap': 'round',
        'stroke-linejoin': 'round',
        width: '0',
        height: '0',
        id: boardId + "_" + side
      }
    };
  };

  boardStackup = function(allLayers, boardId) {
    var bBox, defs, group, height, side, sorted, stack, stackups, svg, val, width, xMax, xMin, xS, xT, yMax, yMin, yS, yT;
    if (allLayers == null) {
      allLayers = [];
    }
    if (boardId == null) {
      boardId = '';
    }
    stackups = {
      top: DEFAULT_SVG('top', boardId),
      bottom: DEFAULT_SVG('bottom', boardId)
    };
    sorted = sortLayers(allLayers, boardId);
    for (side in sorted) {
      val = sorted[side];
      stack = stackLayers(val, boardId);
      defs = {
        defs: {
          _: stack.defs
        }
      };
      group = {
        g: {
          _: stack.group
        }
      };
      svg = stackups[side].svg;
      bBox = stack.bBox;
      xMin = bBox.xMin;
      xMax = bBox.xMax;
      yMin = bBox.yMin;
      yMax = bBox.yMax;
      if (stack.maskId != null) {
        group.g.mask = "url(#" + stack.maskId + ")";
      }
      xT = side === 'top' ? 0 : xMin + xMax;
      yT = yMin + yMax;
      xS = side === 'top' ? 1 : -1;
      yS = -1;
      group.g.transform = "translate(" + xT + "," + yT + ") scale(" + xS + "," + yS + ")";
      svg._ = [defs, group];
      width = bBox.width();
      height = bBox.height();
      svg.width = "" + (width * stack.scale) + stack.units;
      svg.height = "" + (height * stack.scale) + stack.units;
      svg.viewBox = [xMin, yMin, width, height];
    }
    return stackups;
  };

  module.exports = boardStackup;

}).call(this);
