// Generated by CoffeeScript 1.9.3
(function() {
  var Point, find, gatherPoints;

  find = require('lodash.find');

  Point = require('./_point');

  gatherPoints = function(data) {
    var command, firstPoint, index, largeArc, lastPoint, nextPoint, points, radius, sweep, x, y;
    firstPoint = new Point(data[1], data[2]);
    points = [firstPoint];
    index = 3;
    lastPoint = firstPoint;
    while (index < data.length) {
      command = data[index++];
      if (command === 'Z') {
        nextPoint = firstPoint;
      } else {
        if (command === 'A') {
          radius = data[index];
          largeArc = data[index + 3];
          sweep = data[index + 4];
          index += 5;
        }
        x = data[index];
        y = data[index + 1];
        nextPoint = find(points, {
          x: x,
          y: y
        });
        if (nextPoint == null) {
          nextPoint = new Point(x, y);
          points.push(nextPoint);
        }
        index += 2;
      }
      if (command === 'M') {
        firstPoint = nextPoint;
      } else {
        lastPoint.addEdgeTo(nextPoint, radius, largeArc, sweep);
      }
      lastPoint = nextPoint;
    }
    return points;
  };

  module.exports = gatherPoints;

}).call(this);
