name: publish
on:
  push:
    branches: main
    tags: v*

jobs:
  test:
    name: pre-publish test run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn test

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    name: publish packages to npm and site to S3
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - name: build assets
        run: yarn build:all
        env:
          MIXPANEL_ID: ${{ secrets.MIXPANEL_TOKEN }}

      - name: get npm release tag
        id: npm_tag
        run: echo "::set-output name=tag::$(node scripts/get-npm-tag.js ${{ github.ref }})"

      - name: publish to npm with lerna
        run: npm run publish:npm -- --dist-tag ${{ steps.npm_tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: publish to production S3
        run: yarn publish:s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_REGION: us-east-2
          AWS_S3_BUCKET: tracespace.io

  publish-staging:
    name: publish staging site to s3
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - name: build assets
        run: yarn build:all
        env:
          MIXPANEL_ID: ${{ secrets.MIXPANEL_STAGING_TOKEN }}

      - name: publish to S3
        run: yarn publish:s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_REGION: us-east-2
          AWS_S3_BUCKET: staging.tracespace.io
